# syntax=docker/dockerfile:1
# SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
# SPDX-License-Identifier: Apache-2.0

################################################################################

FROM alpine:latest AS slurm-src

ARG SLURM_VERSION=master
ARG SLURM_DIR=slurm
ARG GIT_REPO=git@gitlab.com:SchedMD/dev/slurm.git
ARG GIT_BRANCH=master

WORKDIR /workspace/

# NOTE:
# - if `Permission denied (publickey)`, ssh-agent may lack an identity.
# - Add identity to ssh-agent with `ssh-add ~/.ssh/id_ed25519`.
ADD ${GIT_REPO}#${GIT_BRANCH} ${SLURM_DIR}
